### ISSUE TITLE
[vscode extension 0.8.2 ubuntu foxy ROS2 start command is not ok] 

### ISSUE THREAD

**Issue by yeyanlei** [ms-iot/vscode-ros#745]
(Please add appropriate labels)
- [ ubuntu 20.04] Linux:  (Dist/Version)
- [foxy ] ROS 2: Dist

\<Version of the plugin\>
vscode extension 0.8.2
\<Copy the Version information from the `Help | About` menu\>

# what is the bug
\<current behavior\>
i have a test, foxy is not ok, humble is ok using ros2 start command. vscode extension v0.8.2,   I have posted codes, screenshots and videos.
## Repro steps
\<how to reproduce the bug. Please atta
![ubuntu22 04_ok](https://user-images.githubusercontent.com/36154470/176689117-6699a97d-71a1-47da-b939-10708e963743.png)
ch sample files or github repo if app

https://user-images.githubusercontent.com/36154470/176689134-cd874830-0947-4ead-b244-c821fa04dec2.mp4

ropriate.\>
[ros2_vscode.zip](https://github.com/ms-iot/vscode-ros/files/9020156/ros2_vscode.zip)

![ubuntu20 04_no_ok](https://user-images.githubusercontent.com/36154470/176689059-24666046-df59-4d77-ae5f-c6b89c3fd3d1.png)

# expected behavior
\<what you would expect to happen\>

# additional context
\<any additional information would be helpful for a better understanding\>

**Comment by ooeygui** [comment]
Thank you for posting the videos. One piece of context I'm missing is where is ROS2 installed?
VSCode ROS extension needs to source the ROS environment by itself, so it tries to source `/opt/ros/<distro>/setup.bash`. Is ROS in that location? 

If you have installed ROS elsewhere, you'll need to configure the startup script using the ros.rosSetupScript option in the global or workspace settings, pointing to the specific start script. 

(I'm not able to reproduce this, on my ubuntu 20.04/Foxy setup, which is why I'm asking for more details)

Thanks!

**Comment by yeyanlei** [comment]
i have installed ros, and i have added env    (source /opt/ros/foxy/setup.bash in ~/.bashrc ).  Publishing node is running normally.
[ros2_vscode.zip](https://github.com/ms-iot/vscode-ros/files/9037529/ros2_vscode.zip)
.
