### ISSUE TITLE
[bug] Incompatible with vs code 1.50?

### ISSUE THREAD

**Issue by pitosalas** [ms-iot/vscode-ros#761]
I am running vscode through code-server and I tried installing ms-iot.vscode-ros-0.8.3.vsix and I get the below error.

Am I trying to install the wrong package or is it indeed not compatible with my version of vscode?

Thank you.

<img width="485" alt="Screen Shot 2022-07-24 at 11 16 05 PM" src="https://user-images.githubusercontent.com/44681/180692352-06102ce5-6ce4-47d5-8a99-fd52052f4271.png">

**Comment by ooeygui** [comment]
The type information for VSCode has been moved forward to require VSCode 1.68 in order to match current builds. 

If you need to use an older build of VSCode, you can install an older build of the extension by selecting `Install another version` from the install button:
![image](https://user-images.githubusercontent.com/4564624/180890382-d9f728ac-4f68-4766-b02d-63c7d8d637b5.png)
